### ISSUE TITLE
REDCap Repo

### ISSUE THREAD

**Issue by jasonlones23** [tertek/redcap-pdf-injector#14]
Any chance the changes for this module can be pushed into the REDCap Repo version?  We would love to use this module but cannot currently due to the version we are on.  Thanks!

**Comment by tertek** [comment]
I am not sure if we are talking about the same Repo.

![image](https://user-images.githubusercontent.com/75415872/137859783-e81f870c-0cb6-4eb9-abcf-5dc861a488e1.png)

**Comment by jasonlones23** [comment]
We are. When I actually download, only 1.1.1 comes is loaded. 

Apologies for brevity and/or spelling mistakes as this was sent from my mobile device.

**Comment by tertek** [comment]
In that case you will probably have to upgrade your system. I cannot check but it seems like after Version1.1.1 the minimum requirements for the module have been changed. The current miminum requirements are:

    "compatibility": {
        "php-version-min": "7.0.0",
        "redcap-version-min": "10.0.0"
    }
I advice you to check this together with your IT and ask for further question regarding this in the REDCap community. I am closing this issue because it is not Module related.

**Comment by tertek** [comment]
Have you tried changing the version of the module by clicking on "Enable a module" in Control Center > External Modules?
